//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by eDriven.Gui
// Version: [eDriven.Gui.Editor 2.4.0]
// </auto-generated> 
//------------------------------------------------------------------------------

using eDriven.Core.Geom;
using eDriven.Core.Managers;
using UnityEngine;
using eDriven.Core.Events;
using eDriven.Gui;
using eDriven.Gui.Components;
using eDriven.Gui.Designer;
//using Event=eDriven.Core.Events.Event;

public class MediaQueriesHandlers : MonoBehaviour {

    // fires after the component and its children have been created and layed out
    public void OnCreationComplete(eDriven.Core.Events.Event e)
    {
        SystemManager.Instance.ResizeSignal.Connect(ResizeSlot);
        SetLabelText(SystemManager.Instance.ScreenSize);
    }

    private void ResizeSlot(object[] parameters)
    {
        SetLabelText((Point) parameters[0]);
    }

    private void SetLabelText(Point screenSize)
    {
        var label = GuiLookup.FindComponent<Label>(gameObject, "lblRuler");
        label.Text = string.Format("{0} px", screenSize.X);
    }
}