//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by eDriven.Gui
// Version: [eDriven.Gui.Editor 2.4.0]
// </auto-generated> 
//------------------------------------------------------------------------------

using eDriven.Gui.Containers;
using eDriven.Gui.Managers;
using UnityEngine;
using eDriven.Core.Events;
using eDriven.Gui;
using eDriven.Gui.Components;
using eDriven.Gui.Designer;
using Component = eDriven.Gui.Components.Component;
using Event = eDriven.Core.Events.Event;

//using Event=eDriven.Core.Events.Event;

public class DialogDemoEventHandlers : MonoBehaviour {

    // fires after the GUI component is instantiated
    public void ComponentInstantiated(eDriven.Gui.Components.Component component)
    {
        //eDriven.Gui.Components.Button button = (eDriven.Gui.Components.Button)component;
    }

    // fires after the GUI component is initialized
    public void InitializeComponent(eDriven.Gui.Components.Component component)
    {
        //eDriven.Gui.Components.Button button = (eDriven.Gui.Components.Button)component;
    }

    public void OnClick(eDriven.Core.Events.Event e)
    {
        //eDriven.Core.Events.MouseEvent e2 = (eDriven.Core.Events.MouseEvent)e;
        Component component = GuiLookup.Produce("dialog");
        //Debug.Log("Popping up " + component);
        if (null != component)
            PopupManager.Instance.AddPopup(component, false); // modal = false
    }

    public void RemoveDialog(Event e)
    {
        Button button = e.Target as Button;
        if (button != null)
        {
            Dialog dialog = GuiLookup.FindParent<Dialog>(button);
            PopupManager.Instance.RemovePopup(dialog);
        }
    }


    public void ShowAlert(eDriven.Core.Events.Event e)
    {
        //eDriven.Core.Events.MouseEvent e2 = (eDriven.Core.Events.MouseEvent)e;
        Alert.Show("Foo", "Bar", AlertButtonFlag.Ok);
    }

}
